name: GitHub Actions Demo
run-name: HW for SS, task 1
on: [push]
jobs:
    Explore-GitHub-Actions:
          runs-on: ubuntu-latest
          steps:
                  - run: echo "Hello, GitHub Actions!"
